# Site settings
title: 梦孑渊
description: 木夕のblog
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
#baseurl: "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://wmjtxt.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: wmjtxt
twitter: wmjtxt
github:  wmjtxt

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: wmjtxt #github username
repo: wmjtxt.github.io #github repository
branch: master #branch
#relative_source: ../hanuman/ #source directory
#destination: ../hanuman-pages/ #destination directory
production_url:  https://wmjtxt.github.io
source_url:  https://github.com/wmjtxt/wmjtxt.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
